[package]
name = "phparser"
version = "0.1.0"
authors = ["SirTheViking <alexhexan22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
paris = { git = "https://github.com/SirTheViking/paris" }