[package]
name = "new-york"
version = "0.1.0"
authors = ["Poly <alexhexan22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1.3.1"
futures = "0.3.1"
md5 = "0.7.0"
crossbeam-channel = "0.3.8"
notify = "=5.0.0-pre.1"
paris = { git = "https://github.com/SirTheViking/paris" }