name: Rust Parser Tests

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Build
        uses: actions/checkout@v2
        run: cargo build --verbose
      
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
        
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
    
      - name: Run tests
        run: cargo test --verbose

      
